### ISSUE TITLE
Add option to filter stream services

### ISSUE THREAD

**Issue by VackerSimon** [tvkanters/Dopestreamer#1]
Add an option to filter which stream services should be shown in the drop-down menu.

**Comment by tvkanters** [comment]
Fixed in https://github.com/tvkanters/Dopestreamer/commit/f587cf9d85a59a9c2236198337855515babf3663 https://github.com/tvkanters/Dopestreamer/commit/3956d1102c90f46d5df2d381d2c380e3afde710d https://github.com/tvkanters/Dopestreamer/commit/16dc2f26b710105a62066b7adc753d24f831acb6 https://github.com/tvkanters/Dopestreamer/commit/92f803771b18be439946791cca0385c5f8fbfb56 https://github.com/tvkanters/Dopestreamer/commit/f1ae699f58f88828db1423d54b665c4c065904fc https://github.com/tvkanters/Dopestreamer/commit/f25b860356e3a5e70b88b114f480e2a71c7580c2
